### ISSUE TITLE
Change in folder structure for arguments

### ISSUE THREAD

**Issue by harimasu-ita** [bootphon/abkhazia#12]
[Currently on the decode_fmllr branch, "previously" refers to main branch circa June 2017]

Previously when decoding (for instance), one could manually set the direct path to the [LM] and [AM].
However, now abkhazia seems to look for folders [LM]/language and [AM]/acoustic instead. I imagine that the same might happen for features, after looking at the documentation:

```
(...)
directories:
  <corpus>              abkhazia corpus is read from <corpus>/data. Must be an
                        existing directory, can be relative to the abkhazia
                        data directory ()
  -o <output-dir>, --output-dir <output-dir>
                        output directory, the output data is wrote to <output-
                        dir>/decode, if not specified use <output-
                        dir>=<corpus>.
  -l <lm-dir>, --language-model <lm-dir>
                        the language model recipe directory, data is read from
                        <lm-dir>/language. If not specified, use <lm-
                        dir>=<corpus>.
  -a <am-dir>, --acoustic-model <am-dir>
                        the acoustic model recipe directory, data is read from
                        <am-dir>/acoustic. If not specified, use <am-
                        dir>=<corpus>.
  -f <feat-dir>, --features <feat-dir>
                        the features directory, data is read from <feat-
                        dir>/features. If not specified, use <feat-
                        dir>=<corpus>.
(...)
```

For example: 
```
abkhazia decode [data] -f [features] -a "/home/adriana/Projects/PhD/subprojects/ahpa-ehpe/modeling/corpora/sps_csj/02-new_80-20/split/train/monophone" -l "/home/adriana/Projects/PhD/subprojects/ahpa-ehpe/modeling/corpora/ahpa-corpus/language/unigram/akpa/" -o [output] -v --recipe --force  
```
> fatal error: language model not found: /home/adriana/Projects/PhD/subprojects/ahpa-ehpe/modeling/corpora/ahpa-corpus/language/unigram/akpa/language.
> fatal error: acoustic model not found: /home/adriana/Projects/PhD/subprojects/ahpa-ehpe/modeling/corpora/sps_csj/02-new_80-20/split/train/monophone/acoustic.

Creating the missing folders and filling them with the relevant files (those previously in [LM] and [AM]) solves the issue. However, for me this means doing so for 150 folders in order for my old scripts to run.

Before committing to such restructuring of my files and considering the redundancy of these folders: 
Is this not a bug but a feature? 
 
Thanks in advance!   

Edit: It seems this might have been due to using an old version of abkhazia that was automatically activated in my scripts. Sorry about that.

**Comment by mmmaat** [comment]
Hi :)

Was it a false alert? Can we close the issue?

Thanks!
