### ISSUE TITLE
Is it Python3 friendly ?

### ISSUE THREAD

**Issue by aghriss** [bootphon/abkhazia#14]
I have tried compiling and installing for python3, but I had several issues. Is it python3 friendly ?

**Comment by mmmaat** [comment]
No unfortunately abkhazia is still only available for python2.

**Comment by ayoubriss** [comment]
Is it due to dependencies that are only available for Python2 or is it completely due to the package coding ? 
Thank you

**Comment by mmmaat** [comment]
All the deps can run python3, but the code contains legacy, python2 only, instructions... If you have time and patience you are very welcome to make a pull request for python3 compatibility, by our side we have not time for that :(

**Comment by mmmaat** [comment]
I updated the code to be python>3.6, but it is **no more compatible** with python2. The last python2 release is [abkhazia-0.3.1](https://github.com/bootphon/abkhazia/releases/tag/v0.3.1).
